# Generated by Django 5.0 on 2023-12-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
